# Generated by Django 4.2.8 on 2024-02-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0007_productmodel_category'),
        ('orders_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersDetail',
            new_name='OrdersDetailModel',
        ),
    ]
