# Generated by Django 4.2.8 on 2024-02-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_detail', '0002_rename_ordersdetail_ordersdetailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdetailmodel',
            old_name='orders',
            new_name='order',
        ),
    ]
