# Generated by Django 4.2.8 on 2024-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mark_math', models.IntegerField(blank=True, null=True)),
                ('mark_literature', models.IntegerField(blank=True, null=True)),
                ('mark_english', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
            ],
        ),
    ]
