# Generated by Django 4.2.8 on 2024-02-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersmodel',
            old_name='order_status',
            new_name='status',
        ),
    ]
