# Generated by Django 4.2.8 on 2024-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_status_ordersmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
