# Generated by Django 4.2.8 on 2024-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_no',
            field=models.CharField(blank=True, default='c1898a36-3648-4275-bd72-ed4c712e41b1', max_length=50, null=True),
        ),
    ]
