# Generated by Django 4.2.8 on 2024-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordersmodel_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_no',
            field=models.CharField(default='281cece9-172a-4073-8022-ce104350f124', max_length=50),
        ),
    ]
